### ISSUE TITLE
A question about the migrations

### ISSUE THREAD

**Issue by idan-h** [dudeNumber4/database-migration#2]
Hey! Very nice project.  
  

I have a question regarding to the migrations:  
I have seen that you haven't used sqlcmd to execute the migrations, but SSDT generates sqlcmd code.. Do you need to handle that manually every migration?  
  
  
Also, how to invoke the ps scripts? When I typed their names in the PM Console it says it can't find the commnad...

**Comment by dudeNumber4** [comment]
- There are very few SQLCMD specific instructions generated.  In my powershell script that generates runtime scripts I have a hack that simply removes them.
- In the PM console, you have to actually navigate to the database project root.  That's probably all that is happening there.

**Comment by idan-h** [comment]
Thank you, I since figured it out. Well done with the scripts, this repo should get more traction
